name: M2UMol
channels:
  - pytorch
  - nvidia
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/msys2
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/pro
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/r
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - blas=1.0=mkl
  - boltons=23.0.0=py38h06a4308_0
  - brotlipy=0.7.0=py38h27cfd23_1003
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2023.05.30=h06a4308_0
  - certifi=2023.7.22=py38h06a4308_0
  - cffi=1.14.6=py38h400218f_0
  - chardet=4.0.0=py38h06a4308_1003
  - conda=23.5.2=py38h06a4308_0
  - conda-package-handling=1.7.3=py38h27cfd23_1
  - cryptography=3.4.7=py38hd23ed53_0
  - cuda-cudart=11.7.99=0
  - cuda-cupti=11.7.101=0
  - cuda-libraries=11.7.1=0
  - cuda-nvrtc=11.7.99=0
  - cuda-nvtx=11.7.91=0
  - cuda-runtime=11.7.1=0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.9.0=py38h06a4308_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h295c915_3
  - gmpy2=2.1.2=py38heeb90bb_0
  - gnutls=3.6.15=he1e5248_0
  - idna=2.10=pyhd3eb1b0_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jinja2=3.1.2=py38h06a4308_0
  - jpeg=9e=h7f8727e_0
  - jsonpatch=1.32=pyhd3eb1b0_0
  - jsonpointer=2.1=pyhd3eb1b0_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libcublas=11.10.3.66=0
  - libcufft=10.7.2.124=h4fbf590_0
  - libcufile=1.7.0.149=0
  - libcurand=10.3.3.53=0
  - libcusolver=11.4.0.1=0
  - libcusparse=11.7.4.91=0
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.16=h7f8727e_2
  - libidn2=2.3.2=h7f8727e_0
  - libnpp=11.7.4.75=0
  - libnvjpeg=11.8.0.2=0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libwebp=1.2.2=h55f646e_0
  - libwebp-base=1.2.2=h7f8727e_0
  - lz4-c=1.9.3=h295c915_1
  - markupsafe=2.1.1=py38h7f8727e_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - mpc=1.1.0=h10f8cd9_1
  - mpfr=4.0.2=hb69a4c5_1
  - mpmath=1.2.1=py38h06a4308_0
  - ncurses=6.2=he6710b0_1
  - nettle=3.7.3=hbbd107a_1
  - networkx=2.8.4=py38h06a4308_1
  - numpy-base=1.22.3=py38hf524024_0
  - openh264=2.1.1=h4ff587b_0
  - openssl=1.1.1u=h7f8727e_0
  - pip=21.1.3=py38h06a4308_0
  - pluggy=1.0.0=py38h06a4308_1
  - pycosat=0.6.3=py38h7b6447c_1
  - pycparser=2.20=py_2
  - pyopenssl=20.0.1=pyhd3eb1b0_1
  - pysocks=1.7.1=py38h06a4308_0
  - python=3.8.10=h12debd9_8
  - pytorch=2.0.1=py3.8_cuda11.7_cudnn8.5.0_0
  - pytorch-cuda=11.7=h778d358_5
  - pytorch-mutex=1.0=cuda
  - readline=8.1=h27cfd23_0
  - requests=2.25.1=pyhd3eb1b0_0
  - ruamel_yaml=0.15.100=py38h27cfd23_0
  - setuptools=52.0.0=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - sympy=1.11.1=py38h06a4308_0
  - tk=8.6.10=hbc83047_0
  - toolz=0.12.0=py38h06a4308_0
  - torchaudio=2.0.2=py38_cu117
  - torchtriton=2.0.0=py38
  - tqdm=4.61.2=pyhd3eb1b0_1
  - typing_extensions=4.7.1=py38h06a4308_0
  - urllib3=1.26.6=pyhd3eb1b0_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - xz=5.2.5=h7b6447c_0
  - yaml=0.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
      - dive-into-graphs==1.1.0
      - docutils==0.20.1
      - entrypoints==0.4
      - et-xmlfile==1.1.0
      - executing==0.8.3
      - fastjsonschema==2.15.3
      - fonttools==4.33.3
      - fsspec==2024.3.1
      - future==0.18.3
      - gdown==4.7.1
      - google-auth==2.8.0
      - google-auth-oauthlib==0.4.6
      - grpcio==1.46.3
      - h5py==3.9.0
      - huggingface-hub==0.22.2
      - hydra-core==1.3.2
      - hyperopt==0.2.7
      - imagesize==1.4.1
      - importlib-metadata==4.11.4
      - importlib-resources==5.8.0
      - ipykernel==6.15.0
      - ipython==8.4.0
      - ipython-genutils==0.2.0
      - ipywidgets==7.7.0
      - isort==5.12.0
      - jedi==0.18.1
      - joblib==1.3.1
      - json5==0.9.8
      - jsonschema==4.6.0
      - jupyter-client==7.3.4
      - jupyter-core==4.10.0
      - jupyter-server==1.17.1
      - jupyterlab==3.4.3
      - jupyterlab-language-pack-zh-cn==3.4.post1
      - jupyterlab-pygments==0.2.2
      - jupyterlab-server==2.14.0
      - jupyterlab-widgets==1.1.0
      - kiwisolver==1.4.3
      - littleutils==0.2.2
      - llvmlite==0.40.1
      - markdown==3.3.7
      - matplotlib==3.5.2
      - matplotlib-inline==0.1.3
      - mistune==0.8.4
      - molconfviewer==0.0.2
      - munch==4.0.0
      - mypy-extensions==1.0.0
      - nbclassic==0.3.7
      - nbclient==0.6.4
      - nbconvert==6.5.0
      - nbformat==5.4.0
      - nest-asyncio==1.5.5
      - notebook==6.4.12
      - notebook-shim==0.1.0
      - numba==0.57.1
      - numpy==1.22.4
      - numpydoc==1.5.0
      - oauthlib==3.2.0
      - ogb==1.3.6
      - omegaconf==2.3.0
      - openpyxl==3.1.2
      - outdated==0.2.2
      - packaging==21.3
      - pandas==2.0.3
      - pandocfilters==1.5.0
      - parso==0.8.3
      - pexpect==4.8.0
      - pickleshare==0.7.5
      - pillow==9.1.1
      - prettytable==3.8.0
      - prometheus-client==0.14.1
      - prompt-toolkit==3.0.29
      - protobuf==3.19.4
      - psutil==5.9.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.2
      - py3dmol==2.1.0
      - py4j==0.10.9.7
      - pyasn1==0.4.8
      - pyasn1-modules==0.2.8
      - pycodestyle==2.11.0
      - pydantic==2.3.0
      - pydantic-core==2.6.3
      - pygments==2.16.1
      - pyparsing==3.0.9
      - pyrsistent==0.18.1
      - pyscf==2.3.0
      - python-dateutil==2.8.2
      - pytz==2022.1
      - pyyaml==6.0.1
      - pyzmq==23.2.0
      - rdkit==2023.3.2
      - rdkit-pypi==2022.9.5
      - regex==2023.12.25
      - requests-oauthlib==1.3.1
      - rsa==4.8
      - ruamel-yaml==0.17.32
      - ruamel-yaml-clib==0.2.7
      - safetensors==0.4.2
      - scikit-learn==1.3.0
      - scipy==1.10.1
      - send2trash==1.8.0
      - shap==0.42.1
      - slicer==0.0.7
      - sniffio==1.2.0
      - snowballstemmer==2.2.0
      - soupsieve==2.3.2.post1
      - sphinx==7.1.2
      - sphinxcontrib-applehelp==1.0.4
      - sphinxcontrib-devhelp==1.0.2
      - sphinxcontrib-htmlhelp==2.0.1
      - sphinxcontrib-jsmath==1.0.1
      - sphinxcontrib-qthelp==1.0.3
      - sphinxcontrib-serializinghtml==1.1.5
      - stack-data==0.3.0
      - supervisor==4.2.4
      - tabulate==0.9.0
      - tensorboard==2.9.1
      - tensorboard-data-server==0.6.1
      - tensorboard-plugin-wit==1.8.1
      - terminado==0.15.0
      - threadpoolctl==3.2.0
      - tinycss2==1.1.1
      - tokenizers==0.15.2
      - tomli==2.0.1
      - tornado==6.1
      - traitlets==5.3.0
      - transformers==4.39.2
      - typed-argument-parser==1.7.2
      - typer==0.9.0
      - typing-extensions
      - typing-inspect==0.9.0
      - tzdata==2023.3
      - wcwidth==0.2.5
      - webencodings==0.5.1
      - websocket-client==1.3.3
      - werkzeug==2.1.2
      - widgetsnbextension==3.6.0
      - yacs==0.1.8
      - zipp==3.8.0
prefix: /root/miniconda3
